# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c335ca3c65ec5121620eeef609a6429699d5c4065d0733f53888605a8e6a93ca31d4e861b603a51522abefe0b5ccd5cb6762478bd3e51127e4fb23471065fda7

test:
  secret_key_base: 98c0492506cffbaed1c2ad417fc88728c40b5701ae6b4889da6e7a0ec52b79352e07628bada507f4fab3639980aae67aca2ed657d2b30289a9e47bccdbe76f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
